name: Build and test the application with gradle and build and push a docker image from it

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  build_gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Pull the git repository
      - uses: actions/checkout@v4
      # Download and install Java
      - name: Set up Java Development Kit 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Setting up gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      # Build the project
      - name: Build the application with gradle
        run: ./gradlew build
      # Copy the jar file
      - name: Copy jar file
        run: mv build/libs/perfectify-backend.jar app.jar
      # Upload it as artifact to use in docker build
      - uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: app.jar

  build_docker_file_and_push:
    needs: [ "build_gradle" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: app.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: alystor/perfectify-backend:latest

      - name: "Trigger deployment"
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: "GET"
          headers: '{ "Authorization": "Bearer ${{ secrets.WEBHOOK_ACCESS_TOKEN }}" }'
